### ISSUE TITLE
Allow use of @apply in gcss

### ISSUE THREAD

**Issue by vendion** [yosssi/gcss#16]
I'm trying to use Gcss with [polymer](https://www.polymer-project.org) and some of the components require the use `@apply` in the CSS.  Currently `gcss` strips these tags out when compiled.  It would be helpful if when compiling `gcss` would ignore such tags.

To see an example of how these are used see https://github.com/PolymerElements/iron-flex-layout/blob/master/demo/x-app.html

Example gcss file

```
html, body
  height: 100%

body
  margin: 0

:host
  @apply(--layout-horizontal)
  @apply(--paper-font-body2)

[nav]
  @apply(--layout-vertical)
  width: 200px
  background-color: var(--paper-grey-300)
```

Generated css

``` css
html,body{height:100%;}body{margin:0;}[nav]{width:200px;background-color:var(--paper-grey-300);}
```
