### ISSUE TITLE
Allow variables in the middle of a statement

### ISSUE THREAD

**Issue by vendion** [yosssi/gcss#8]
Using the following GCSS I have a `$base-fonts` variable I have some common fonts defined, and I have custom fonts before and after the variable.  The problem is when the variable is surrounded by static items the variable seems to get skipped.

GCSS file (surrounded variable)

```
$color1: #2e6580
$color2: #3a83a7
$color3: #509ec4
$color4: #75b3d2
$color5: #9bc9df
$base-fonts: 'Helvetica Neue', Helvetica, Arial

h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6
  font-family: 'Droid Serif', $base-fonts, serif
  color: $color1
  a,a:hover,u
    color: $color1
    text-decoration: none
  small
    color: $color2

body
  font-family: 'Roboto', $base-fonts, sans-serif

footer
  margin-top: 10px
```

Produces

``` css
h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6 {
    font-family: 'Droid Serif', serif;
    color: #2e6580;
}

h1 a,h1 a:hover,h1 u,h2 a,h2 a:hover,h2 u,h3 a,h3 a:hover,h3 u,h4 a,h4 a:hover,h4 u,h5 a,h5 a:hover,h5 u,h6 a,h6 a:hover,h6 u,.h1 a,.h1 a:hover,.h1 u,.h2 a,.h2 a:hover,.h2 u,.h3 a,.h3 a:hover,.h3 u,.h4 a,.h4 a:hover,.h4 u,.h5 a,.h5 a:hover,.h5 u,.h6 a,.h6 a:hover,.h6 u {
    color: #2e6580;
    text-decoration: none;
}

h1 small,h2 small,h3 small,h4 small,h5 small,h6 small,.h1 small,.h2 small,.h3 small,.h4 small,.h5 small,.h6 small {
    color: #3a83a7;
}

body {
    font-family: 'Roboto', sans-serif;
}

footer {
    margin-top: 10px;
}
```

Removing the `serif` and `sans-serif` the `$base-fonts` works as expected.
